USE tstore;

CREATE TABLE book(
	seq BIGINT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	creator VARCHAR(255) NOT NULL,
	publisher VARCHAR(255) NOT NULL,
	pubDate DATE);
	
SHOW TABLES;
DESC book;

CREATE TABLE USER(
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	userId VARCHAR(50) NOT NULL,
	name VARCHAR(100) NOT NULL,
	pwd VARCHAR(300) NOT NULL,
	tel VARCHAR(20),
	email VARCHAR(200),
	regDate DATETIME DEFAULT CURRENT_TIMESTAMP(),
	UNIQUE KEY uk_name(userId, email));

	
CREATE TABLE userRoles(
	userId BIGINT AUTO_INCREMENT PRIMARY KEY,
	roleId INT);
	
CREATE TABLE ROLE(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL);