CREATE DATABASE edumon;
USE edumon;

CREATE TABLE test1(
	no INT primary key AUTO_INCREMENT,
	id VARCHAR(20),
	com VARCHAR(2000));
	
INSERT INTO test1 VALUES (DEFAULT, 'kim','코멘트1');
INSERT INTO test1 VALUES (DEFAULT, 'lee','코멘트2');

COMMIT;

SELECT * FROM test1;

CREATE TABLE userInfo(
	NO INT PRIMARY KEY AUTO_INCREMENT,
	userId VARCHAR(20) NOT NULL,
	userName VARCHAR(50),
	PASSWORD VARCHAR(50),
	email VARCHAR(50),
	tel VARCHAR(20),
	regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	POINT INT DEFAULT 0,
	active INT DEFAULT 1,
	authorities INT DEFAULT 0,
	authority INT DEFAULT 0,
	authorityNm INT DEFAULT 0,
	auth INT DEFAULT 0);
	
