server:
  port: 8085
# spring boot 설정 jsp 설정 (/src/main/webapp/WEB-INF/view)
spirng:
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp

# maria db 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/edumon
    username: root
    password: 1234

# MyBatis 설정
mybatis:
  type-aliases-package: com.chunjae
  mapper-locations: mappers/**/*.xml
